name: Deploy Mrs. Violet Noire Website

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci --only=production || echo "No package-lock.json found, skipping npm install"

    - name: Deploy to Hostinger via SFTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.HOSTINGER_FTP_HOST }}
        username: ${{ secrets.HOSTINGER_FTP_USER }}
        password: ${{ secrets.HOSTINGER_FTP_PASS }}
        server-dir: public_html/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.vscode/**
          **/.github/**
          **/scripts/**
          **/terraform/**
          **/config/**
          **/.env*
          **/README.md
          **/package*.json
          **/*.md

    - name: Test deployment
      run: |
        echo "🧪 Testing deployment..."
        sleep 10

        # Test main page
        if curl -s https://mrsvioletnoire.com/ | grep -q "Mrs. Violet Noire"; then
          echo "✅ Main page is loading correctly"
        else
          echo "⚠️ Main page may not be loading properly"
          exit 1
        fi

        # Test CSS
        if curl -s https://mrsvioletnoire.com/css/style.css | grep -q "Mrs. Violet Noire"; then
          echo "✅ CSS is loading correctly"
        else
          echo "⚠️ CSS may not be loading properly"
        fi

        echo "🎉 Deployment successful!"
